/*
 * This file is generated by jOOQ.
 */
package ru.panic.generatedClasses.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import ru.panic.generatedClasses.tables.Games;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GamesRecord extends UpdatableRecordImpl<GamesRecord> implements Record8<Long, Double, String, String, String, Long, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.games.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.games.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.games.amount</code>.
     */
    public void setAmount(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.games.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>public.games.currency</code>.
     */
    public void setCurrency(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.games.currency</code>.
     */
    public String getCurrency() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.games.game</code>.
     */
    public void setGame(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.games.game</code>.
     */
    public String getGame() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.games.game_state</code>.
     */
    public void setGameState(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.games.game_state</code>.
     */
    public String getGameState() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.games.timestamp</code>.
     */
    public void setTimestamp(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.games.timestamp</code>.
     */
    public Long getTimestamp() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.games.user_id</code>.
     */
    public void setUserId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.games.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.games.username</code>.
     */
    public void setUsername(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.games.username</code>.
     */
    public String getUsername() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Double, String, String, String, Long, Long, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Double, String, String, String, Long, Long, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Games.GAMES.ID;
    }

    @Override
    public Field<Double> field2() {
        return Games.GAMES.AMOUNT;
    }

    @Override
    public Field<String> field3() {
        return Games.GAMES.CURRENCY;
    }

    @Override
    public Field<String> field4() {
        return Games.GAMES.GAME;
    }

    @Override
    public Field<String> field5() {
        return Games.GAMES.GAME_STATE;
    }

    @Override
    public Field<Long> field6() {
        return Games.GAMES.TIMESTAMP;
    }

    @Override
    public Field<Long> field7() {
        return Games.GAMES.USER_ID;
    }

    @Override
    public Field<String> field8() {
        return Games.GAMES.USERNAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Double component2() {
        return getAmount();
    }

    @Override
    public String component3() {
        return getCurrency();
    }

    @Override
    public String component4() {
        return getGame();
    }

    @Override
    public String component5() {
        return getGameState();
    }

    @Override
    public Long component6() {
        return getTimestamp();
    }

    @Override
    public Long component7() {
        return getUserId();
    }

    @Override
    public String component8() {
        return getUsername();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Double value2() {
        return getAmount();
    }

    @Override
    public String value3() {
        return getCurrency();
    }

    @Override
    public String value4() {
        return getGame();
    }

    @Override
    public String value5() {
        return getGameState();
    }

    @Override
    public Long value6() {
        return getTimestamp();
    }

    @Override
    public Long value7() {
        return getUserId();
    }

    @Override
    public String value8() {
        return getUsername();
    }

    @Override
    public GamesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GamesRecord value2(Double value) {
        setAmount(value);
        return this;
    }

    @Override
    public GamesRecord value3(String value) {
        setCurrency(value);
        return this;
    }

    @Override
    public GamesRecord value4(String value) {
        setGame(value);
        return this;
    }

    @Override
    public GamesRecord value5(String value) {
        setGameState(value);
        return this;
    }

    @Override
    public GamesRecord value6(Long value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public GamesRecord value7(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public GamesRecord value8(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public GamesRecord values(Long value1, Double value2, String value3, String value4, String value5, Long value6, Long value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GamesRecord
     */
    public GamesRecord() {
        super(Games.GAMES);
    }

    /**
     * Create a detached, initialised GamesRecord
     */
    public GamesRecord(Long id, Double amount, String currency, String game, String gameState, Long timestamp, Long userId, String username) {
        super(Games.GAMES);

        setId(id);
        setAmount(amount);
        setCurrency(currency);
        setGame(game);
        setGameState(gameState);
        setTimestamp(timestamp);
        setUserId(userId);
        setUsername(username);
        resetChangedOnNotNull();
    }
}
