/*
 * This file is generated by jOOQ.
 */
package ru.panic.generatedClasses;


import ru.panic.generatedClasses.tables.Games;
import ru.panic.generatedClasses.tables.Replenishments;
import ru.panic.generatedClasses.tables.Users;
import ru.panic.generatedClasses.tables.Withdrawals;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.games</code>.
     */
    public static final Games GAMES = Games.GAMES;

    /**
     * The table <code>public.replenishments</code>.
     */
    public static final Replenishments REPLENISHMENTS = Replenishments.REPLENISHMENTS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.withdrawals</code>.
     */
    public static final Withdrawals WITHDRAWALS = Withdrawals.WITHDRAWALS;
}
